apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sTLSIngress
metadata:
  name: require-tls-ingress
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
    namespaceSelector:
      matchLabels:
        pci-cde: "true"
